# Auto-generated Concept Mapping

CONCEPT_DEFINITIONS = {
    "CONCEPT_10_TEN": {'label': '10. ten', 'sinhala': 'දහය', 'synonyms': ['දහය', '10']},
    "CONCEPT_11_ELEVEN": {'label': '11. eleven', 'sinhala': 'එකොළහ', 'synonyms': ['එකොළහ', '11']},
    "CONCEPT_12_TWELVE": {'label': '12. twelve', 'sinhala': 'දොළහ', 'synonyms': ['දොළහ', '12']},
    "CONCEPT_13_THIRTEEN": {'label': '13. thirteen', 'sinhala': 'දහතුන', 'synonyms': ['දහතුන', '13']},
    "CONCEPT_14_FOURTEEN": {'label': '14. fourteen', 'sinhala': 'දහහතර', 'synonyms': ['දහහතර', '14']},
    "CONCEPT_15_FIFTEEN": {'label': '15. fifteen', 'sinhala': 'පහළොව', 'synonyms': ['පහළොව', '15']},
    "CONCEPT_16_SIXTEEN": {'label': '16. sixteen', 'sinhala': 'දහසය', 'synonyms': ['දහසය', '16']},
    "CONCEPT_17_SEVENTEEN": {'label': '17. seventeen', 'sinhala': 'දහහත', 'synonyms': ['දහහත', '17']},
    "CONCEPT_18_EIGHTEEN": {'label': '18. eighteen', 'sinhala': 'දහඅට', 'synonyms': ['දහඅට', '18']},
    "CONCEPT_19_NINETEEN": {'label': '19. nineteen', 'sinhala': 'දහනවය', 'synonyms': ['දහනවය', '19']},
    "CONCEPT_1_ONE": {'label': '1. one', 'sinhala': 'එක', 'synonyms': ['එක', '1', 'එකක්']},
    "CONCEPT_20_TWENTY": {'label': '20. twenty', 'sinhala': 'විස්ස', 'synonyms': ['විස්ස', '20']},
    "CONCEPT_2_TWO": {'label': '2. two', 'sinhala': 'දෙක', 'synonyms': ['දෙක', '2']},
    "CONCEPT_3_THREE": {'label': '3. three', 'sinhala': 'තුන', 'synonyms': ['තුන', '3']},
    "CONCEPT_4_FOUR": {'label': '4. four', 'sinhala': 'හතර', 'synonyms': ['හතර', '4']},
    "CONCEPT_5_FIVE": {'label': '5. five', 'sinhala': 'පහ', 'synonyms': ['පහ', '5']},
    "CONCEPT_6_SIX": {'label': '6. six', 'sinhala': 'හය', 'synonyms': ['හය', '6']},
    "CONCEPT_7_SEVEN": {'label': '7. seven', 'sinhala': 'හත', 'synonyms': ['හත', '7']},
    "CONCEPT_8_EIGHT": {'label': '8. eight', 'sinhala': 'අට', 'synonyms': ['අට', '8']},
    "CONCEPT_9_NINE": {'label': '9. nine', 'sinhala': 'නවය', 'synonyms': ['නවය', '9']},
    "CONCEPT_ADDITION": {'label': 'Addition', 'sinhala': 'එකතු කිරීම', 'synonyms': ['එකතු කිරීම']},
    "CONCEPT_AFTER": {'label': 'After', 'sinhala': 'පස්සේ', 'synonyms': ['පස්සේ', 'පසුව']},
    "CONCEPT_AGAIN": {'label': 'Again', 'sinhala': 'නැවත', 'synonyms': ['නැවත', 'ආයෙත්']},
    "CONCEPT_AIRPORT": {'label': 'Airport', 'sinhala': 'ගුවන් තොටුපල', 'synonyms': ['ගුවන් තොටුපල', 'එයාර්පෝට්']},
    "CONCEPT_ALLOW": {'label': 'Allow', 'sinhala': 'ඉඩ දෙනවා', 'synonyms': ['ඉඩ දෙනවා', 'Allow']},
    "CONCEPT_ALRIGHT": {'label': 'Alright', 'sinhala': 'හරි', 'synonyms': ['හරි']},
    "CONCEPT_ALSO": {'label': 'Also', 'sinhala': 'තවද', 'synonyms': ['තවද']},
    "CONCEPT_ANGRY": {'label': 'Angry', 'sinhala': 'තරහයි', 'synonyms': ['තරහයි', 'කේන්තිය', 'කෝපය']},
    "CONCEPT_APRIL": {'label': 'April', 'sinhala': 'අප්\u200dරේල්', 'synonyms': ['අප්\u200dරේල්']},
    "CONCEPT_AROUND": {'label': 'Around', 'sinhala': 'වටේ', 'synonyms': ['වටේ', 'වටා']},
    "CONCEPT_ARTICLE": {'label': 'Article', 'sinhala': 'ලිපිය', 'synonyms': ['ලිපිය']},
    "CONCEPT_AUGUST": {'label': 'August', 'sinhala': 'අගෝස්තු', 'synonyms': ['අගෝස්තු']},
    "CONCEPT_AUNT": {'label': 'Aunt', 'sinhala': 'නැන්දා', 'synonyms': ['නැන්දා', 'නැන්දේ']},
    "CONCEPT_AYUBOWAN": {'label': 'Ayubowan', 'sinhala': 'ආයුබෝවන්', 'synonyms': ['ආයුබෝවන්']},
    "CONCEPT_BABY": {'label': 'Baby', 'sinhala': 'බිළිඳා', 'synonyms': ['බිළිඳා']},
    "CONCEPT_BAD": {'label': 'Bad', 'sinhala': 'නරක', 'synonyms': ['නරක']},
    "CONCEPT_BAG": {'label': 'Bag', 'sinhala': 'බෑගය', 'synonyms': ['බෑගය', 'බෑග් එක']},
    "CONCEPT_BANK": {'label': 'Bank', 'sinhala': 'බැංකුව', 'synonyms': ['බැංකුව', 'බැංකු']},
    "CONCEPT_BATHE": {'label': 'Bathe', 'sinhala': 'නානවා', 'synonyms': ['නානවා', 'නාන්න', 'නෑවා', 'සිරුර සෝදනවා']},
    "CONCEPT_BEAUTIFUL": {'label': 'Beautiful', 'sinhala': 'ලස්සන', 'synonyms': ['ලස්සන', 'Beautiful']},
    "CONCEPT_BED": {'label': 'Bed', 'sinhala': 'ඇඳ', 'synonyms': ['ඇඳ']},
    "CONCEPT_BICYCLE": {'label': 'Bicycle', 'sinhala': 'බයිසිකලය', 'synonyms': ['බයිසිකලය', 'බයිසිකල්', 'පාපැදිය']},
    "CONCEPT_BIRD": {'label': 'Bird', 'sinhala': 'කුරුල්ලා', 'synonyms': ['කුරුල්ලා', 'කුරුල්ලෝ']},
    "CONCEPT_BLACK": {'label': 'Black', 'sinhala': 'කළු', 'synonyms': ['කළු', 'කලු']},
    "CONCEPT_BLUE": {'label': 'Blue', 'sinhala': 'නිල්', 'synonyms': ['නිල්']},
    "CONCEPT_BOAT": {'label': 'Boat', 'sinhala': 'බෝට්ටුව', 'synonyms': ['බෝට්ටුව', 'බෝට්ටු']},
    "CONCEPT_BOIL": {'label': 'Boil', 'sinhala': 'නටනවා', 'synonyms': ['නටනවා', 'තම්බනවා', 'තම්බන්න', 'තැම්බුවා', 'උණු කරනවා']},
    "CONCEPT_BOOK": {'label': 'Book', 'sinhala': 'පොත', 'synonyms': ['පොත', 'පොත්', 'ග්\u200dරන්ථය']},
    "CONCEPT_BREAK": {'label': 'Break', 'sinhala': 'කඩනවා', 'synonyms': ['කඩනවා', 'කඩන්න', 'කැඩුවා']},
    "CONCEPT_BRING": {'label': 'Bring', 'sinhala': 'ගෙනෙනවා', 'synonyms': ['ගෙනෙනවා', 'ගෙනෙන්න', 'ගෙනාවා']},
    "CONCEPT_BRO": {'label': 'Bro', 'sinhala': 'සහෝදරයා', 'synonyms': ['සහෝදරයා']},
    "CONCEPT_BROTHER_IN_LAW": {'label': 'Brother in law', 'sinhala': 'මස්සිනා', 'synonyms': ['මස්සිනා']},
    "CONCEPT_BROWN": {'label': 'Brown', 'sinhala': 'දුඹුරු', 'synonyms': ['දුඹුරු']},
    "CONCEPT_BUS": {'label': 'Bus', 'sinhala': 'බස් එක', 'synonyms': ['බස් එක', 'බස්', 'බස් රථය']},
    "CONCEPT_BUS_STATION": {'label': 'Bus station', 'sinhala': 'බස් නැවතුම', 'synonyms': ['බස් නැවතුම', 'බස් ස්ටෑන්ඩ් එක']},
    "CONCEPT_BUY": {'label': 'Buy', 'sinhala': 'Buy', 'synonyms': ['Buy', 'මිලදී ගන්නවා', 'මිලදී ගත්තා']},
    "CONCEPT_CAMERA": {'label': 'Camera', 'sinhala': ' කැමරාව', 'synonyms': [' කැමරාව', 'කැමරාව']},
    "CONCEPT_CAN": {'label': 'Can', 'sinhala': 'පුළුවන්', 'synonyms': ['පුළුවන්']},
    "CONCEPT_CANT": {'label': 'Cant', 'sinhala': 'බෑ', 'synonyms': ['බෑ', 'බැහැ']},
    "CONCEPT_CAR": {'label': 'Car', 'sinhala': 'කාර් එක', 'synonyms': ['කාර් එක', 'කාර්', 'කාර් රථය']},
    "CONCEPT_CARD": {'label': 'Card', 'sinhala': 'කාඩ්පත', 'synonyms': ['කාඩ්පත', 'කාඩ් එක']},
    "CONCEPT_CAREFUL": {'label': 'Careful', 'sinhala': 'පරිස්සමින්', 'synonyms': ['පරිස්සමින්', 'පරිස්සමෙන්']},
    "CONCEPT_CARROT": {'label': 'Carrot', 'sinhala': 'කැරට්', 'synonyms': ['කැරට්']},
    "CONCEPT_CARRY": {'label': 'Carry', 'sinhala': 'ගෙනියනවා', 'synonyms': ['ගෙනියනවා', 'ගෙනියන්න', 'ගෙනිච්චා']},
    "CONCEPT_CAT": {'label': 'Cat', 'sinhala': 'බළලා', 'synonyms': ['බළලා', 'පූසා', 'පූසෝ', 'පූසෙක්']},
    "CONCEPT_CEILING_FAN": {'label': 'Ceiling fan', 'sinhala': 'විදුලි පංකාව', 'synonyms': ['විදුලි පංකාව', 'ෆෑන් එක']},
    "CONCEPT_CELL_PHONE": {'label': 'Cell phone', 'sinhala': 'මොබයිල්', 'synonyms': ['මොබයිල්', 'Cell phone']},
    "CONCEPT_CHAIN": {'label': 'Chain', 'sinhala': 'දාමය', 'synonyms': ['දාමය', 'මාලය']},
    "CONCEPT_CHAIR": {'label': 'Chair', 'sinhala': 'පුටුව', 'synonyms': ['පුටුව', 'පුටු']},
    "CONCEPT_CHANGE": {'label': 'Change', 'sinhala': 'වෙනස් කරනවා', 'synonyms': ['වෙනස් කරනවා', 'වෙනස් කරන්න', 'වෙනස් කළා']},
    "CONCEPT_CHILD": {'label': 'Child', 'sinhala': 'ළමයා', 'synonyms': ['ළමයා', 'බබා', 'දරුවා', 'පොඩ්ඩා']},
    "CONCEPT_CHILDREN": {'label': 'Children', 'sinhala': 'ළමයි', 'synonyms': ['ළමයි']},
    "CONCEPT_CHOICE": {'label': 'Choice', 'sinhala': 'තේරීම', 'synonyms': ['තේරීම']},
    "CONCEPT_CHOOSE": {'label': 'Choose', 'sinhala': 'Choose', 'synonyms': ['Choose']},
    "CONCEPT_CHURCH": {'label': 'Church', 'sinhala': 'පල්ලිය', 'synonyms': ['පල්ලිය', 'පල්ලි']},
    "CONCEPT_CLEARLY": {'label': 'Clearly', 'sinhala': 'පැහැදිලිව', 'synonyms': ['පැහැදිලිව']},
    "CONCEPT_CLICK": {'label': 'Click', 'sinhala': 'ක්ලික් කරනවා', 'synonyms': ['ක්ලික් කරනවා', 'ක්ලික් කරන්න', 'ක්ලික් කළා']},
    "CONCEPT_CLOTHING": {'label': 'Clothing', 'sinhala': 'ඇඳුම්', 'synonyms': ['ඇඳුම්']},
    "CONCEPT_COLD": {'label': 'Cold', 'sinhala': 'සීතල', 'synonyms': ['සීතල']},
    "CONCEPT_COLOR": {'label': 'Color', 'sinhala': 'පාට', 'synonyms': ['පාට', 'වර්ණ']},
    "CONCEPT_COME": {'label': 'Come', 'sinhala': 'එනවා', 'synonyms': ['එනවා', 'එන්න', 'ආවා', 'එමු', 'එන්නම්']},
    "CONCEPT_COMPUTER": {'label': 'Computer', 'sinhala': 'පරිගණකය', 'synonyms': ['පරිගණකය', 'කොම්පියුටරය']},
    "CONCEPT_CONNECT": {'label': 'Connect', 'sinhala': 'සම්බන්ධ කරනවා', 'synonyms': ['සම්බන්ධ කරනවා', 'සම්බන්ධ කරන්න', 'සම්බන්ධ කළා', 'සම්බන්ධ']},
    "CONCEPT_COOK": {'label': 'Cook', 'sinhala': 'උයනවා', 'synonyms': ['උයනවා', 'උයන්න', 'ඉව්වා']},
    "CONCEPT_COPY": {'label': 'Copy', 'sinhala': 'පිටපත් කරනවා', 'synonyms': ['පිටපත් කරනවා', 'පිටපත් කරන්න', 'පිටපත් කළා', 'පිටපත්']},
    "CONCEPT_COUGH": {'label': 'Cough', 'sinhala': 'කහිනවා', 'synonyms': ['කහිනවා', 'කහින්න', 'කැස්සා']},
    "CONCEPT_COUNT": {'label': 'Count', 'sinhala': 'ගණන් කරනවා', 'synonyms': ['ගණන් කරනවා', 'ගණන් කරන්න']},
    "CONCEPT_COVER": {'label': 'Cover', 'sinhala': 'වහනවා', 'synonyms': ['වහනවා', 'වහන්න', 'වැහුවා']},
    "CONCEPT_COW": {'label': 'Cow', 'sinhala': 'එළදෙන', 'synonyms': ['එළදෙන', 'එළ හරකා', 'එළදෙනුන්']},
    "CONCEPT_CROCODILE": {'label': 'Crocodile', 'sinhala': 'කිඹුලා', 'synonyms': ['කිඹුලා', 'කිඹුලෝ', 'කිඹුලෙක්']},
    "CONCEPT_CRY": {'label': 'Cry', 'sinhala': 'අඬනවා', 'synonyms': ['අඬනවා', 'අඬන්න', 'අඬුවා']},
    "CONCEPT_CULTURE": {'label': 'Culture', 'sinhala': 'සංස්කෘතිය', 'synonyms': ['සංස්කෘතිය']},
    "CONCEPT_CUP": {'label': 'Cup', 'sinhala': 'කෝප්පය', 'synonyms': ['කෝප්පය']},
    "CONCEPT_CUT": {'label': 'Cut', 'sinhala': 'කපනවා', 'synonyms': ['කපනවා', 'කපන්න', 'කැපුවා']},
    "CONCEPT_DANCE": {'label': 'Dance', 'sinhala': 'නටන්න', 'synonyms': ['නටන්න', 'නැටුවා']},
    "CONCEPT_DAUGHTER": {'label': 'Daughter', 'sinhala': 'දුව', 'synonyms': ['දුව', 'දුවේ', 'පැංචි']},
    "CONCEPT_DAY": {'label': 'Day', 'sinhala': 'දවස', 'synonyms': ['දවස', 'දින']},
    "CONCEPT_DAY_AFTER_TOMORROW": {'label': 'Day after tomorrow', 'sinhala': 'අනිද්දා', 'synonyms': ['අනිද්දා']},
    "CONCEPT_DEAF": {'label': 'Deaf', 'sinhala': 'බිහිරි', 'synonyms': ['බිහිරි', 'ගොළු']},
    "CONCEPT_DECEMBER": {'label': 'December', 'sinhala': 'දෙසැම්බර්', 'synonyms': ['දෙසැම්බර්']},
    "CONCEPT_DEEP": {'label': 'Deep', 'sinhala': 'ගැඹුරු', 'synonyms': ['ගැඹුරු', 'වැදගත්']},
    "CONCEPT_DESK": {'label': 'Desk', 'sinhala': 'ඩෙස්ක් එක', 'synonyms': ['ඩෙස්ක් එක']},
    "CONCEPT_DIFFERENT": {'label': 'Different', 'sinhala': 'වෙනස්', 'synonyms': ['වෙනස්']},
    "CONCEPT_DIFFICULT": {'label': 'Difficult', 'sinhala': 'අමාරු', 'synonyms': ['අමාරු', 'Difficult', 'අසීරු']},
    "CONCEPT_DIVIDE": {'label': 'Divide', 'sinhala': 'බෙදීම', 'synonyms': ['බෙදීම']},
    "CONCEPT_DOCTOR": {'label': 'Doctor', 'sinhala': 'දොස්තර', 'synonyms': ['දොස්තර', 'වෛද්\u200dයවරයා']},
    "CONCEPT_DOG": {'label': 'Dog', 'sinhala': 'බල්ලා', 'synonyms': ['බල්ලා', 'බල්ලෝ']},
    "CONCEPT_DONE": {'label': 'Done', 'sinhala': 'ඉවරයි', 'synonyms': ['ඉවරයි', 'ඉවර']},
    "CONCEPT_DONT": {'label': 'Dont', 'sinhala': 'එපා', 'synonyms': ['එපා', 'කරන්න එපා']},
    "CONCEPT_DONT_KNOW": {'label': 'Dont know', 'sinhala': 'දන්නේ නෑ', 'synonyms': ['දන්නේ නෑ', 'දන්නෙ නෑ']},
    "CONCEPT_DOOR": {'label': 'Door', 'sinhala': 'දොර', 'synonyms': ['දොර', 'දොරවල්']},
    "CONCEPT_DOUBLE": {'label': 'Double', 'sinhala': 'ඩබල්', 'synonyms': ['ඩබල්']},
    "CONCEPT_DRAW": {'label': 'Draw', 'sinhala': 'අඳිනවා', 'synonyms': ['අඳිනවා', 'අඳින්න', 'ඇන්දා']},
    "CONCEPT_DRINK": {'label': 'Drink', 'sinhala': 'බොනවා', 'synonyms': ['බොනවා', 'බිව්වා', 'බොන්න', 'බොමු']},
    "CONCEPT_EAR": {'label': 'Ear', 'sinhala': 'කන', 'synonyms': ['කන']},
    "CONCEPT_EAT": {'label': 'Eat', 'sinhala': 'කනවා', 'synonyms': ['කනවා', 'කෑවා', 'කන්න', 'කමු']},
    "CONCEPT_ELDER_BRO": {'label': 'Elder bro', 'sinhala': 'අයියා', 'synonyms': ['අයියා', 'අයියේ', 'අයිය']},
    "CONCEPT_ELDER_SISTER": {'label': 'Elder sister', 'sinhala': 'අක්කා', 'synonyms': ['අක්කා', 'අක්කේ', 'අක්ක', 'අක්කි']},
    "CONCEPT_ELEPHANT": {'label': 'Elephant', 'sinhala': 'අලියා', 'synonyms': ['අලියා', 'අලි', 'අලියෙක්']},
    "CONCEPT_ENTER": {'label': 'Enter', 'sinhala': 'ඇතුල් වෙනවා', 'synonyms': ['ඇතුල් වෙනවා', 'ඇතුල් වෙන්න', 'ඇතුල් වුනා']},
    "CONCEPT_EQUAL": {'label': 'Equal', 'sinhala': 'සමානයි', 'synonyms': ['සමානයි']},
    "CONCEPT_ERASE": {'label': 'Erase', 'sinhala': 'මකනවා', 'synonyms': ['මකනවා', 'මකන්න', 'මැකුවා']},
    "CONCEPT_EVENING": {'label': 'Evening', 'sinhala': 'සවස', 'synonyms': ['සවස', 'හවස']},
    "CONCEPT_EXCHANGE": {'label': 'Exchange', 'sinhala': 'මාරු කරනවා', 'synonyms': ['මාරු කරනවා', 'මාරු කරන්න', 'මාරු කළා', 'හුවමාරු කරනවා']},
    "CONCEPT_EYE": {'label': 'Eye', 'sinhala': 'ඇස', 'synonyms': ['ඇස']},
    "CONCEPT_EYES": {'label': 'Eyes', 'sinhala': 'ඇස්', 'synonyms': ['ඇස්']},
    "CONCEPT_FACE": {'label': 'Face', 'sinhala': 'මුහුණ', 'synonyms': ['මුහුණ']},
    "CONCEPT_FAMILIES": {'label': 'Families', 'sinhala': 'පවුල්', 'synonyms': ['පවුල්']},
    "CONCEPT_FAMILY": {'label': 'Family', 'sinhala': 'පවුල', 'synonyms': ['පවුල']},
    "CONCEPT_FAST": {'label': 'Fast', 'sinhala': 'වේගයෙන්', 'synonyms': ['වේගයෙන්', 'වේගවත්']},
    "CONCEPT_FAT": {'label': 'Fat', 'sinhala': 'මහත', 'synonyms': ['මහත', 'තරබාරු']},
    "CONCEPT_FATHER": {'label': 'Father', 'sinhala': 'තාත්තා', 'synonyms': ['තාත්තා', 'තාත්තේ', 'තාත්ත', 'පියා', 'අප්පච්චි', 'තාත්තාම', 'තාත්තාගේ', 'තාත්ති']},
    "CONCEPT_FEAR": {'label': 'Fear', 'sinhala': 'බය', 'synonyms': ['බය', 'භය']},
    "CONCEPT_FEBRUARY": {'label': 'February', 'sinhala': 'පෙබරවාරි', 'synonyms': ['පෙබරවාරි']},
    "CONCEPT_FEEL": {'label': 'Feel', 'sinhala': 'දැනෙනවා', 'synonyms': ['දැනෙනවා', 'දැනුනා']},
    "CONCEPT_FEVER": {'label': 'Fever', 'sinhala': 'උණ', 'synonyms': ['උණ']},
    "CONCEPT_FIGHT": {'label': 'Fight', 'sinhala': 'රණ්ඩු වෙනවා', 'synonyms': ['රණ්ඩු වෙනවා', 'රණ්ඩු වෙන්න', 'රණ්ඩු වුනා', 'සටන් කරනවා']},
    "CONCEPT_FISH": {'label': 'Fish', 'sinhala': 'මාළුවා', 'synonyms': ['මාළුවා', 'මාළු']},
    "CONCEPT_FLOWER": {'label': 'Flower', 'sinhala': 'මල', 'synonyms': ['මල', 'මල්']},
    "CONCEPT_FOLLOW": {'label': 'Follow', 'sinhala': 'අනුගමනය කරනවා', 'synonyms': ['අනුගමනය කරනවා', 'අනුගමනය කරන්න', 'අනුගමනය කළා']},
    "CONCEPT_FOOD": {'label': 'Food', 'sinhala': 'කෑම', 'synonyms': ['කෑම', 'ආහාර']},
    "CONCEPT_FREE": {'label': 'Free', 'sinhala': 'නොමිලේ', 'synonyms': ['නොමිලේ', 'නිදහස්']},
    "CONCEPT_FRIDAY": {'label': 'Friday', 'sinhala': 'සිකුරාදා', 'synonyms': ['සිකුරාදා']},
    "CONCEPT_FRIEND": {'label': 'Friend', 'sinhala': 'යාළුවා', 'synonyms': ['යාළුවා', 'යාළුවෝ', 'යාළුවෙ', 'මිතුරේ']},
    "CONCEPT_FULL": {'label': 'Full', 'sinhala': 'පිරුණු', 'synonyms': ['පිරුණු']},
    "CONCEPT_GET_UP": {'label': 'Get up', 'sinhala': 'නැගිටිනවා', 'synonyms': ['නැගිටිනවා', 'නැගිටින්න', 'නැගිට්ටා']},
    "CONCEPT_GIVE": {'label': 'Give', 'sinhala': 'දෙනවා', 'synonyms': ['දෙනවා', 'දෙන්න', 'දුන්නා']},
    "CONCEPT_GO": {'label': 'Go', 'sinhala': 'යනවා', 'synonyms': ['යනවා', 'යන්න', 'ගියා', 'යමු', 'යන්නම්']},
    "CONCEPT_GOLD": {'label': 'Gold', 'sinhala': 'රත්තරන්', 'synonyms': ['රත්තරන්', 'රන්']},
    "CONCEPT_GOOD": {'label': 'Good', 'sinhala': 'හොඳයි', 'synonyms': ['හොඳයි', 'හොඳ']},
    "CONCEPT_GOOD_EVENING": {'label': 'Good evening', 'sinhala': 'සුබ සැන්දෑවක්', 'synonyms': ['සුබ සැන්දෑවක්']},
    "CONCEPT_GOOD_MORNING": {'label': 'Good morning', 'sinhala': 'සුබ උදෑසනක්', 'synonyms': ['සුබ උදෑසනක්']},
    "CONCEPT_GOOD_NIGHT": {'label': 'Good night', 'sinhala': 'සුබ රාත්\u200dරියක්', 'synonyms': ['සුබ රාත්\u200dරියක්']},
    "CONCEPT_GRAND_FATHER": {'label': 'Grand father', 'sinhala': 'සීය', 'synonyms': ['සීය', 'සීයා', 'සීයේ', 'මුත්තා']},
    "CONCEPT_GRAND_MOTHER": {'label': 'Grand mother', 'sinhala': 'ආච්චි', 'synonyms': ['ආච්චි', 'ආච්චී', 'කිරි අම්මා', 'ආච්චියේ']},
    "CONCEPT_GRAND_SON": {'label': 'Grand son', 'sinhala': 'මුනුපුරා', 'synonyms': ['මුනුපුරා']},
    "CONCEPT_GREEN": {'label': 'Green', 'sinhala': 'කොළ', 'synonyms': ['කොළ']},
    "CONCEPT_GREY": {'label': 'Grey', 'sinhala': 'අළු', 'synonyms': ['අළු', 'Gray', 'අළු පාට']},
    "CONCEPT_GROUP": {'label': 'Group', 'sinhala': 'කණ්ඩායම', 'synonyms': ['කණ්ඩායම', 'Group']},
    "CONCEPT_GUIDE": {'label': 'Guide', 'sinhala': 'Guide', 'synonyms': ['Guide']},
    "CONCEPT_GUN": {'label': 'Gun', 'sinhala': 'තුවක්කුව', 'synonyms': ['තුවක්කුව']},
    "CONCEPT_HAIR": {'label': 'Hair', 'sinhala': 'කොණ්ඩය', 'synonyms': ['කොණ්ඩය']},
    "CONCEPT_HAND": {'label': 'Hand', 'sinhala': 'අත', 'synonyms': ['අත']},
    "CONCEPT_HANG": {'label': 'Hang', 'sinhala': 'එල්ලනවා', 'synonyms': ['එල්ලනවා', 'එල්ලන්න', 'එල්ලුවා']},
    "CONCEPT_HAPPY": {'label': 'Happy', 'sinhala': 'සතුටුයි', 'synonyms': ['සතුටුයි', 'සතුට', 'සන්තෝසයි', 'සතුටු']},
    "CONCEPT_HARD": {'label': 'Hard', 'sinhala': 'තද', 'synonyms': ['තද', 'ගල්']},
    "CONCEPT_HAT": {'label': 'Hat', 'sinhala': 'තොප්පිය', 'synonyms': ['තොප්පිය']},
    "CONCEPT_HE": {'label': 'He', 'sinhala': 'එයා', 'synonyms': ['එයා', 'ඔහු', 'ඔහුව']},
    "CONCEPT_HEAD": {'label': 'Head', 'sinhala': 'ඔළුව', 'synonyms': ['ඔළුව']},
    "CONCEPT_HEALTH": {'label': 'Health', 'sinhala': 'සෞඛ්\u200dය', 'synonyms': ['සෞඛ්\u200dය', 'සෞඛ්\u200dයය']},
    "CONCEPT_HEALTHY": {'label': 'Healthy', 'sinhala': 'නිරෝගී', 'synonyms': ['නිරෝගී']},
    "CONCEPT_HEAR": {'label': 'Hear', 'sinhala': 'ඇහෙනවා', 'synonyms': ['ඇහෙනවා', 'ඇහුනා']},
    "CONCEPT_HELLO": {'label': 'Hello', 'sinhala': 'හෙලෝ', 'synonyms': ['හෙලෝ', 'හායි']},
    "CONCEPT_HELP": {'label': 'Help', 'sinhala': 'උදව්', 'synonyms': ['උදව්', 'උදව් කරනවා', 'උදව් කරන්න', 'උදව් කළා', 'Help']},
    "CONCEPT_HERE": {'label': 'Here', 'sinhala': 'මෙහෙ', 'synonyms': ['මෙහෙ', 'මෙතන']},
    "CONCEPT_HIGH": {'label': 'High', 'sinhala': 'උස', 'synonyms': ['උස']},
    "CONCEPT_HILL": {'label': 'Hill', 'sinhala': 'කන්ද', 'synonyms': ['කන්ද']},
    "CONCEPT_HIT": {'label': 'Hit', 'sinhala': 'ගහනවා', 'synonyms': ['ගහනවා', 'ගහන්න', 'ගැහුවා']},
    "CONCEPT_HOSPITAL": {'label': 'Hospital', 'sinhala': 'රෝහල', 'synonyms': ['රෝහල', 'ඉස්පිරිතාලෙ', 'හොස්පිට්ල්', 'සුවසෙවන']},
    "CONCEPT_HOUR": {'label': 'Hour', 'sinhala': 'පැය', 'synonyms': ['පැය']},
    "CONCEPT_HOUSE": {'label': 'House', 'sinhala': 'ගෙදර', 'synonyms': ['ගෙදර', 'නිවස', 'ගේ', 'ගෙවල්', 'Home', 'ගෙය', 'නිවහන']},
    "CONCEPT_HOW_ARE_YOU": {'label': 'How are you', 'sinhala': 'කොහොමද', 'synonyms': ['කොහොමද', 'සැප සනීප']},
    "CONCEPT_HOW_MANY": {'label': 'How many', 'sinhala': 'කොච්චර', 'synonyms': ['කොච්චර', 'කොච්චරද']},
    "CONCEPT_HOW_MUCH": {'label': 'How much', 'sinhala': 'කොපමණ', 'synonyms': ['කොපමණ', 'කීයද']},
    "CONCEPT_HUSBAND": {'label': 'Husband', 'sinhala': 'සැමියා', 'synonyms': ['සැමියා', 'මහත්තයා']},
    "CONCEPT_I": {'label': 'I', 'sinhala': 'මම', 'synonyms': ['මම', 'මට', 'මා', 'මාව', 'මං', 'මන්', 'මමයි']},
    "CONCEPT_IMPACT": {'label': 'Impact', 'sinhala': 'බලපෑම', 'synonyms': ['බලපෑම', 'Effect']},
    "CONCEPT_IN": {'label': 'In', 'sinhala': 'තුල', 'synonyms': ['තුල', 'ඇතුලෙ']},
    "CONCEPT_INDEPENDENT": {'label': 'Independent', 'sinhala': 'ස්වාධීන', 'synonyms': ['ස්වාධීන']},
    "CONCEPT_INSIDE": {'label': 'Inside', 'sinhala': 'ඇතුලේ', 'synonyms': ['ඇතුලේ', 'ඇතුළත']},
    "CONCEPT_INSTEAD": {'label': 'Instead', 'sinhala': 'ඒ වෙනුවට', 'synonyms': ['ඒ වෙනුවට', 'වෙනුවට']},
    "CONCEPT_INTERNET": {'label': 'Internet', 'sinhala': 'අන්තර්ජාලය', 'synonyms': ['අන්තර්ජාලය', 'ඉන්ටර්නෙට්']},
    "CONCEPT_I_KNOW": {'label': 'I know', 'sinhala': 'මම දන්නවා', 'synonyms': ['මම දන්නවා', 'දන්නවා']},
    "CONCEPT_JANUARY": {'label': 'January', 'sinhala': 'ජනවාරි', 'synonyms': ['ජනවාරි']},
    "CONCEPT_JULY": {'label': 'July', 'sinhala': 'ජූලි', 'synonyms': ['ජූලි']},
    "CONCEPT_JUMP": {'label': 'Jump', 'sinhala': 'පනිනවා', 'synonyms': ['පනිනවා', 'පනින්න', 'පැන්නා']},
    "CONCEPT_JUNE": {'label': 'June', 'sinhala': 'ජූනි', 'synonyms': ['ජූනි']},
    "CONCEPT_KEY": {'label': 'Key', 'sinhala': 'යතුර', 'synonyms': ['යතුර']},
    "CONCEPT_KNIFE": {'label': 'Knife', 'sinhala': 'පිහිය', 'synonyms': ['පිහිය']},
    "CONCEPT_KNOCK": {'label': 'Knock', 'sinhala': 'තට්ටු කරනවා', 'synonyms': ['තට්ටු කරනවා', 'තට්ටු කරන්න', 'තට්ටු කළා']},
    "CONCEPT_LADY": {'label': 'Lady', 'sinhala': 'කාන්තාව', 'synonyms': ['කාන්තාව', 'ගෑණු', 'වනිතාව']},
    "CONCEPT_LAPTOP": {'label': 'Laptop', 'sinhala': 'ලැප්ටොප්', 'synonyms': ['ලැප්ටොප්', 'ලැප්ටොප් එක']},
    "CONCEPT_LAUGH": {'label': 'Laugh', 'sinhala': 'හිනාවෙනවා', 'synonyms': ['හිනාවෙනවා', 'හිනා වුනා']},
    "CONCEPT_LEAD": {'label': 'Lead', 'sinhala': 'මඟ පෙන්වනවා', 'synonyms': ['මඟ පෙන්වනවා']},
    "CONCEPT_LEG": {'label': 'Leg', 'sinhala': 'කකුල', 'synonyms': ['කකුල']},
    "CONCEPT_LESS": {'label': 'Less', 'sinhala': 'Less', 'synonyms': ['Less']},
    "CONCEPT_LET": {'label': 'Let', 'sinhala': 'ඉඩ දෙන්න', 'synonyms': ['ඉඩ දෙන්න']},
    "CONCEPT_LIKE": {'label': 'Like', 'sinhala': 'කැමතියි', 'synonyms': ['කැමතියි', 'කැමති']},
    "CONCEPT_LION": {'label': 'Lion', 'sinhala': 'සිංහයා', 'synonyms': ['සිංහයා', 'සිංහයෝ']},
    "CONCEPT_LIST": {'label': 'List', 'sinhala': 'ලැයිස්තුව', 'synonyms': ['ලැයිස්තුව']},
    "CONCEPT_LISTEN": {'label': 'Listen', 'sinhala': 'අහනවා', 'synonyms': ['අහනවා', 'අහන්න', 'ඇහුවා', 'ඇහුම්කන් දෙනවා']},
    "CONCEPT_LOCATION": {'label': 'Location', 'sinhala': 'ස්ථානය', 'synonyms': ['ස්ථානය', 'තැන']},
    "CONCEPT_LOCK": {'label': 'Lock', 'sinhala': 'අගුල', 'synonyms': ['අගුල']},
    "CONCEPT_LOOSE": {'label': 'Loose', 'sinhala': 'බුරුල්', 'synonyms': ['බුරුල්']},
    "CONCEPT_LOVE": {'label': 'Love', 'sinhala': 'ආදරෙයි', 'synonyms': ['ආදරෙයි', 'ආදරය', 'ආදරය කරනවා']},
    "CONCEPT_LOW": {'label': 'Low', 'sinhala': 'අඩු', 'synonyms': ['අඩු']},
    "CONCEPT_MAKE": {'label': 'Make', 'sinhala': 'හදනවා', 'synonyms': ['හදනවා', 'හදන්න', 'හැදුවා']},
    "CONCEPT_MAN": {'label': 'Man', 'sinhala': 'මිනිහා', 'synonyms': ['මිනිහා', 'පිරිමි', 'පුද්ගලයා']},
    "CONCEPT_MARCH": {'label': 'March', 'sinhala': 'මාර්තු', 'synonyms': ['මාර්තු']},
    "CONCEPT_MAY": {'label': 'May', 'sinhala': 'මැයි', 'synonyms': ['මැයි']},
    "CONCEPT_MEDICINE": {'label': 'Medicine', 'sinhala': 'බෙහෙත්', 'synonyms': ['බෙහෙත්', 'ඖෂධ']},
    "CONCEPT_MEET": {'label': 'Meet', 'sinhala': 'හමුවෙනවා', 'synonyms': ['හමුවෙනවා', 'හමුවෙන්න', 'හමු වුනා']},
    "CONCEPT_MIDDLE": {'label': 'Middle', 'sinhala': 'මැද', 'synonyms': ['මැද']},
    "CONCEPT_MILK": {'label': 'Milk', 'sinhala': 'කිරි', 'synonyms': ['කිරි']},
    "CONCEPT_MIND": {'label': 'Mind', 'sinhala': 'මනස', 'synonyms': ['මනස']},
    "CONCEPT_MINUTES": {'label': 'Minutes', 'sinhala': 'විනාඩි', 'synonyms': ['විනාඩි']},
    "CONCEPT_MONDAY": {'label': 'Monday', 'sinhala': 'සඳුදා', 'synonyms': ['සඳුදා']},
    "CONCEPT_MONEY": {'label': 'Money', 'sinhala': 'මුදල්', 'synonyms': ['මුදල්', 'සල්ලි']},
    "CONCEPT_MONKEY": {'label': 'Monkey', 'sinhala': 'වඳුරා', 'synonyms': ['වඳුරා', 'වඳුරෝ']},
    "CONCEPT_MONTH": {'label': 'Month', 'sinhala': 'මාසය', 'synonyms': ['මාසය']},
    "CONCEPT_MONTHS": {'label': 'Months', 'sinhala': 'මාස', 'synonyms': ['මාස']},
    "CONCEPT_MOON": {'label': 'Moon', 'sinhala': 'හඳ', 'synonyms': ['හඳ', 'චන්ද්\u200dරයා']},
    "CONCEPT_MORNING": {'label': 'Morning', 'sinhala': 'උදේ', 'synonyms': ['උදේ', 'උදෑසන']},
    "CONCEPT_MOTHER": {'label': 'Mother', 'sinhala': 'අම්මා', 'synonyms': ['අම්මා', 'අම්මේ', 'අම්ම', 'මව', 'මෑණියන්', 'අම්මි']},
    "CONCEPT_MOTORCYCLE": {'label': 'Motorcycle', 'sinhala': 'මෝටර් සයිකලය', 'synonyms': ['මෝටර් සයිකලය', 'මෝටර් සයිකල්', 'බයික් එක']},
    "CONCEPT_MOUTH": {'label': 'Mouth', 'sinhala': 'කට', 'synonyms': ['කට']},
    "CONCEPT_MOVIE": {'label': 'Movie', 'sinhala': 'චිත්\u200dරපටය', 'synonyms': ['චිත්\u200dරපටය', 'ෆිල්ම්', 'චිත්\u200dරපටිය', 'ෆිල්ම් එක']},
    "CONCEPT_MULTIPLICATION": {'label': 'Multiplication', 'sinhala': 'ගුණ කිරීම', 'synonyms': ['ගුණ කිරීම']},
    "CONCEPT_MY": {'label': 'My', 'sinhala': 'මගේ', 'synonyms': ['මගේ']},
    "CONCEPT_NEAR": {'label': 'Near', 'sinhala': 'ළඟ', 'synonyms': ['ළඟ', 'අසල']},
    "CONCEPT_NETWORK": {'label': 'Network', 'sinhala': 'ජාලය', 'synonyms': ['ජාලය']},
    "CONCEPT_NEVER": {'label': 'Never', 'sinhala': 'කවදාවත්', 'synonyms': ['කවදාවත්']},
    "CONCEPT_NEXT": {'label': 'Next', 'sinhala': 'ඊළඟ', 'synonyms': ['ඊළඟ']},
    "CONCEPT_NEXT_DOOR": {'label': 'Next door', 'sinhala': 'අල්ලපු ගෙදර', 'synonyms': ['අල්ලපු ගෙදර']},
    "CONCEPT_NIGHT": {'label': 'Night', 'sinhala': 'රාත්\u200dරිය', 'synonyms': ['රාත්\u200dරිය', 'රෑ']},
    "CONCEPT_NO": {'label': 'No', 'sinhala': 'නෑ', 'synonyms': ['නෑ', 'නැහැ']},
    "CONCEPT_NONE": {'label': 'None', 'sinhala': 'කිසිවක් නැත', 'synonyms': ['කිසිවක් නැත']},
    "CONCEPT_NOSE": {'label': 'Nose', 'sinhala': 'නහය', 'synonyms': ['නහය']},
    "CONCEPT_NOT_GOOD": {'label': 'Not good', 'sinhala': 'හොඳ නෑ', 'synonyms': ['හොඳ නෑ']},
    "CONCEPT_NOT_LIKE": {'label': 'Not like', 'sinhala': 'කැමති නැහැ', 'synonyms': ['කැමති නැහැ', 'අකමැතියි']},
    "CONCEPT_NOT_LIKE_(DISLIKE)": {'label': 'Not like (dislike)', 'sinhala': 'කැමති නෑ', 'synonyms': ['කැමති නෑ']},
    "CONCEPT_NOVEMBER": {'label': 'November', 'sinhala': 'නොවැම්බර්', 'synonyms': ['නොවැම්බර්']},
    "CONCEPT_NOW": {'label': 'Now', 'sinhala': 'දැන්', 'synonyms': ['දැන්']},
    "CONCEPT_OCTOBER": {'label': 'October', 'sinhala': 'ඔක්තෝබර්', 'synonyms': ['ඔක්තෝබර්']},
    "CONCEPT_OLD": {'label': 'Old', 'sinhala': 'පරණ', 'synonyms': ['පරණ', 'වයසක']},
    "CONCEPT_ON": {'label': 'On', 'sinhala': 'මත', 'synonyms': ['මත']},
    "CONCEPT_OPEN": {'label': 'Open', 'sinhala': 'අරිනවා', 'synonyms': ['අරිනවා', 'විවෘත කරනවා', 'ඇරියා']},
    "CONCEPT_OR": {'label': 'Or', 'sinhala': 'හෝ', 'synonyms': ['හෝ', 'නැත්නම්']},
    "CONCEPT_ORANGE": {'label': 'Orange', 'sinhala': 'තැඹිලි', 'synonyms': ['තැඹිලි']},
    "CONCEPT_ORDER": {'label': 'Order', 'sinhala': 'ඇණවුම් කරනවා', 'synonyms': ['ඇණවුම් කරනවා', 'ඇණවුම් කරන්න', 'ඇණවුම් කළා']},
    "CONCEPT_OUR": {'label': 'Our', 'sinhala': 'අපේ', 'synonyms': ['අපේ']},
    "CONCEPT_OUT": {'label': 'Out', 'sinhala': 'එළියෙ', 'synonyms': ['එළියෙ', 'පිටත']},
    "CONCEPT_OVER": {'label': 'Over', 'sinhala': 'උඩින්', 'synonyms': ['උඩින්']},
    "CONCEPT_PAINT": {'label': 'Paint', 'sinhala': 'තීන්ත', 'synonyms': ['තීන්ත']},
    "CONCEPT_PART": {'label': 'Part', 'sinhala': 'කොටස', 'synonyms': ['කොටස']},
    "CONCEPT_PAST": {'label': 'Past', 'sinhala': 'අතීත', 'synonyms': ['අතීත']},
    "CONCEPT_PATH": {'label': 'Path', 'sinhala': 'මාර්ගය', 'synonyms': ['මාර්ගය']},
    "CONCEPT_PEACE": {'label': 'Peace', 'sinhala': 'සාමය', 'synonyms': ['සාමය']},
    "CONCEPT_PEEING": {'label': 'Peeing', 'sinhala': 'චූ කරනවා', 'synonyms': ['චූ කරනවා', 'චූ කරන්න']},
    "CONCEPT_PEN": {'label': 'Pen', 'sinhala': 'පෑන', 'synonyms': ['පෑන', 'පෑන්']},
    "CONCEPT_PENCIL": {'label': 'Pencil', 'sinhala': 'පැන්සල', 'synonyms': ['පැන්සල']},
    "CONCEPT_PEOPLE": {'label': 'People', 'sinhala': 'මිනිස්සු', 'synonyms': ['මිනිස්සු', 'ජනතාව']},
    "CONCEPT_PHONE": {'label': 'Phone', 'sinhala': 'ජංගම දුරකථනය', 'synonyms': ['ජංගම දුරකථනය', 'ෆෝන් එක']},
    "CONCEPT_PINK": {'label': 'Pink', 'sinhala': 'රෝස', 'synonyms': ['රෝස']},
    "CONCEPT_PLANE": {'label': 'Plane', 'sinhala': 'ප්ලේන් එක', 'synonyms': ['ප්ලේන් එක', 'ගුවන් යානය', 'ප්ලේන්']},
    "CONCEPT_PLATE": {'label': 'Plate', 'sinhala': 'පීරිසිය', 'synonyms': ['පීරිසිය', 'පිඟාන']},
    "CONCEPT_PLAY": {'label': 'Play', 'sinhala': 'සෙල්ලම් කරනවා', 'synonyms': ['සෙල්ලම් කරනවා', 'සෙල්ලම් කරන්න', 'සෙල්ලම් කළා', 'සෙල්ලම්', 'Play']},
    "CONCEPT_PLAYER": {'label': 'Player', 'sinhala': 'ක්\u200dරීඩකයා', 'synonyms': ['ක්\u200dරීඩකයා']},
    "CONCEPT_POCKET": {'label': 'Pocket', 'sinhala': ' සාක්කුව', 'synonyms': [' සාක්කුව', 'සාක්කුව']},
    "CONCEPT_POINT": {'label': 'Point', 'sinhala': 'ලක්ෂ්\u200dයය', 'synonyms': ['ලක්ෂ්\u200dයය', 'Point']},
    "CONCEPT_POLICE": {'label': 'Police', 'sinhala': 'පොලිස්', 'synonyms': ['පොලිස්', 'රාළහාමි']},
    "CONCEPT_POLICE_STATION": {'label': 'Police station', 'sinhala': 'පොලිසිය', 'synonyms': ['පොලිසිය', 'පොලිස් ස්ථානය']},
    "CONCEPT_POSITIVE": {'label': 'Positive', 'sinhala': 'ධනාත්මක', 'synonyms': ['ධනාත්මක']},
    "CONCEPT_PRESENT": {'label': 'Present', 'sinhala': 'වර්තමාන', 'synonyms': ['වර්තමාන']},
    "CONCEPT_PROBLEM": {'label': 'Problem', 'sinhala': 'ප්\u200dරශ්නය', 'synonyms': ['ප්\u200dරශ්නය']},
    "CONCEPT_PULL": {'label': 'Pull', 'sinhala': 'අදිනවා', 'synonyms': ['අදිනවා', 'අදින්න', 'ඇද්දා']},
    "CONCEPT_PURPLE": {'label': 'Purple', 'sinhala': 'දම්', 'synonyms': ['දම්']},
    "CONCEPT_PUT": {'label': 'Put', 'sinhala': 'දානවා', 'synonyms': ['දානවා', 'දාන්න', 'දැම්මා']},
    "CONCEPT_QUICK": {'label': 'Quick', 'sinhala': 'ඉක්මන්', 'synonyms': ['ඉක්මන්']},
    "CONCEPT_QUICKLY": {'label': 'Quickly', 'sinhala': 'ඉක්මනට', 'synonyms': ['ඉක්මනට']},
    "CONCEPT_RABBIT": {'label': 'Rabbit', 'sinhala': 'හාවා', 'synonyms': ['හාවා', 'හාවෝ', 'හාවෙක්']},
    "CONCEPT_RADIO": {'label': 'Radio', 'sinhala': 'ගුවන් විදුලිය', 'synonyms': ['ගුවන් විදුලිය', 'රේඩියෝව']},
    "CONCEPT_READ": {'label': 'Read', 'sinhala': 'කියවනවා', 'synonyms': ['කියවනවා', 'කියවන්න']},
    "CONCEPT_RED": {'label': 'Red', 'sinhala': 'රතු', 'synonyms': ['රතු']},
    "CONCEPT_RELATIONS": {'label': 'Relations', 'sinhala': 'නෑදෑයෝ', 'synonyms': ['නෑදෑයෝ']},
    "CONCEPT_RICE": {'label': 'Rice', 'sinhala': 'බත්', 'synonyms': ['බත්']},
    "CONCEPT_RICH": {'label': 'Rich', 'sinhala': 'පොහොසත්', 'synonyms': ['පොහොසත්', 'සල්ලි තියෙන']},
    "CONCEPT_RING": {'label': 'Ring', 'sinhala': 'මුද්ද', 'synonyms': ['මුද්ද']},
    "CONCEPT_ROAD": {'label': 'Road', 'sinhala': 'පාර', 'synonyms': ['පාර']},
    "CONCEPT_RUN": {'label': 'Run', 'sinhala': 'දුවනවා', 'synonyms': ['දුවනවා', 'දුවන්න', 'දිව්වා']},
    "CONCEPT_SAD": {'label': 'Sad', 'sinhala': 'දුක', 'synonyms': ['දුක', 'කණගාටු', 'දුකයි']},
    "CONCEPT_SAME": {'label': 'Same', 'sinhala': 'එකම', 'synonyms': ['එකම']},
    "CONCEPT_SAND": {'label': 'Sand', 'sinhala': 'වැලි', 'synonyms': ['වැලි']},
    "CONCEPT_SAREE": {'label': 'Saree', 'sinhala': 'සාරිය', 'synonyms': ['සාරිය']},
    "CONCEPT_SATURDAY": {'label': 'Saturday', 'sinhala': 'සෙනසුරාදා', 'synonyms': ['සෙනසුරාදා']},
    "CONCEPT_SCHOOL": {'label': 'School', 'sinhala': 'පාසල', 'synonyms': ['පාසල', 'ඉස්කෝලේ', 'විදුහල', 'ඉස්කෝලෙ', 'විද්\u200dයාලය']},
    "CONCEPT_SCRATCH": {'label': 'Scratch', 'sinhala': 'කසනවා', 'synonyms': ['කසනවා', 'කසන්න', 'කැසුවා']},
    "CONCEPT_SEARCH": {'label': 'Search', 'sinhala': 'හොයනවා', 'synonyms': ['හොයනවා', 'හොයන්න', 'හෙව්වා']},
    "CONCEPT_SECONDS": {'label': 'Seconds', 'sinhala': 'තත්පර', 'synonyms': ['තත්පර']},
    "CONCEPT_SEE": {'label': 'See', 'sinhala': 'පේනවා', 'synonyms': ['පේනවා', 'දැක්කා', 'දකිනවා', 'දකින්න']},
    "CONCEPT_SELECT": {'label': 'Select', 'sinhala': 'තෝරනවා', 'synonyms': ['තෝරනවා', 'තෝරන්න', 'තේරුවා', 'තෝරාගන්නවා']},
    "CONCEPT_SELL": {'label': 'Sell', 'sinhala': 'විකුණනවා', 'synonyms': ['විකුණනවා', 'විකුණන්න', 'විකුනුවා']},
    "CONCEPT_SENIOR": {'label': 'Senior', 'sinhala': 'ජ්\u200dයෙෂ්ඨ', 'synonyms': ['ජ්\u200dයෙෂ්ඨ']},
    "CONCEPT_SEPTEMBER": {'label': 'September', 'sinhala': 'සැප්තැම්බර්', 'synonyms': ['සැප්තැම්බර්']},
    "CONCEPT_SHARE": {'label': 'Share', 'sinhala': 'බෙදාගෙන', 'synonyms': ['බෙදාගෙන']},
    "CONCEPT_SHIRT": {'label': 'Shirt', 'sinhala': 'කමිසය', 'synonyms': ['කමිසය', 'ෂර්ට් එක']},
    "CONCEPT_SHOP": {'label': 'Shop', 'sinhala': 'කඩේ', 'synonyms': ['කඩේ', 'කඩ', 'වෙළඳසැල', 'සාප්පුව']},
    "CONCEPT_SHOW": {'label': 'Show', 'sinhala': 'පෙන්වනවා', 'synonyms': ['පෙන්වනවා', 'පෙන්වන්න', 'පෙන්නුවා']},
    "CONCEPT_SIGN": {'label': 'Sign', 'sinhala': 'සලකුණ', 'synonyms': ['සලකුණ', 'ලකුණ']},
    "CONCEPT_SIGN_LANGUAGE": {'label': 'Sign language', 'sinhala': 'සංඥා භාෂාව', 'synonyms': ['සංඥා භාෂාව']},
    "CONCEPT_SISTER": {'label': 'Sister', 'sinhala': 'සහෝදරිය', 'synonyms': ['සහෝදරිය']},
    "CONCEPT_SISTER_IN_LAW": {'label': 'Sister in law', 'sinhala': 'නෑනා', 'synonyms': ['නෑනා']},
    "CONCEPT_SIT": {'label': 'Sit', 'sinhala': 'වාඩි වෙනවා', 'synonyms': ['වාඩි වෙනවා', 'ඉඳගන්න', 'වාඩි වුනා', 'වාඩිවෙනවා', 'වාඩිවෙන්න']},
    "CONCEPT_SKIRT": {'label': 'Skirt', 'sinhala': 'සාය', 'synonyms': ['සාය']},
    "CONCEPT_SLEEP": {'label': 'Sleep', 'sinhala': 'නිදා ගන්නවා', 'synonyms': ['නිදා ගන්නවා', 'නිදාගන්න', 'නිදාගන්නවා', 'නිදා ගත්තා', 'බුදියනවා']},
    "CONCEPT_SMALL": {'label': 'Small', 'sinhala': 'පොඩි', 'synonyms': ['පොඩි', 'පුංචි']},
    "CONCEPT_SMILE": {'label': 'Smile', 'sinhala': 'හිනා වෙනවා', 'synonyms': ['හිනා වෙනවා', 'හිනා', 'Smile']},
    "CONCEPT_SNAKE": {'label': 'Snake', 'sinhala': 'නයා', 'synonyms': ['නයා', 'නයින්']},
    "CONCEPT_SOCIETY": {'label': 'Society', 'sinhala': 'සමාජය', 'synonyms': ['සමාජය']},
    "CONCEPT_SOFT": {'label': 'Soft', 'sinhala': 'මෘදු', 'synonyms': ['මෘදු']},
    "CONCEPT_SON": {'label': 'Son', 'sinhala': 'පුතා', 'synonyms': ['පුතා', 'පුතේ', 'පිරිමි ළමයා']},
    "CONCEPT_SONG": {'label': 'Song', 'sinhala': 'සින්දුව', 'synonyms': ['සින්දුව', 'ගීතය', 'සිංදුව']},
    "CONCEPT_SPOON": {'label': 'Spoon', 'sinhala': 'හැන්ද', 'synonyms': ['හැන්ද']},
    "CONCEPT_SQUIRREL": {'label': 'Squirrel', 'sinhala': 'ලේනා', 'synonyms': ['ලේනා']},
    "CONCEPT_STOMACH": {'label': 'Stomach', 'sinhala': 'බඩ', 'synonyms': ['බඩ']},
    "CONCEPT_STOP": {'label': 'Stop', 'sinhala': 'නවත්වන්න', 'synonyms': ['නවත්වන්න', 'නවතින්න', 'නැවැත්තුවා']},
    "CONCEPT_STREET": {'label': 'Street', 'sinhala': 'වීදිය', 'synonyms': ['වීදිය']},
    "CONCEPT_STRONG": {'label': 'Strong', 'sinhala': 'ශක්තිමත්', 'synonyms': ['ශක්තිමත්']},
    "CONCEPT_STRUCTURE": {'label': 'Structure', 'sinhala': 'හැට්ටය', 'synonyms': ['හැට්ටය', 'ව්\u200dයුහය']},
    "CONCEPT_STUDENT": {'label': 'Student', 'sinhala': 'ශිෂ්\u200dයයා', 'synonyms': ['ශිෂ්\u200dයයා']},
    "CONCEPT_STUDY": {'label': 'Study', 'sinhala': 'පාඩම් කරනවා', 'synonyms': ['පාඩම් කරනවා', 'පාඩම් කරන්න', 'පාඩම් කළා', 'ඉගෙනගන්න']},
    "CONCEPT_SUBTRACTION": {'label': 'Subtraction', 'sinhala': 'අඩු කිරීම', 'synonyms': ['අඩු කිරීම']},
    "CONCEPT_SUIT": {'label': 'Suit', 'sinhala': 'ඇඳුම', 'synonyms': ['ඇඳුම']},
    "CONCEPT_SUNDAY": {'label': 'Sunday', 'sinhala': 'ඉරිදා', 'synonyms': ['ඉරිදා']},
    "CONCEPT_SWEEP": {'label': 'Sweep', 'sinhala': 'අතු ගානවා', 'synonyms': ['අතු ගානවා', 'අතු ගාන්න', 'අතු ගෑවා']},
    "CONCEPT_SWIM": {'label': 'Swim', 'sinhala': 'පීනනවා', 'synonyms': ['පීනනවා', 'පීනන්න', 'පීනුවා']},
    "CONCEPT_TABLE": {'label': 'Table', 'sinhala': 'මේසය', 'synonyms': ['මේසය', 'මේස']},
    "CONCEPT_TAKE": {'label': 'Take', 'sinhala': 'ගන්නවා', 'synonyms': ['ගන්නවා', 'ගන්න', 'ගත්තා']},
    "CONCEPT_TALK": {'label': 'Talk', 'sinhala': 'කතා කරනවා', 'synonyms': ['කතා කරනවා', 'කතා කරන්න', 'කතා කළා', 'කතා', ' කියන්න', 'Speak', 'Say']},
    "CONCEPT_TEA": {'label': 'Tea', 'sinhala': 'තේ', 'synonyms': ['තේ']},
    "CONCEPT_TEACH": {'label': 'Teach', 'sinhala': 'උගන්වනවා', 'synonyms': ['උගන්වනවා', 'උගන්වන්න', 'ඉගැන්නුවා']},
    "CONCEPT_TEACHER": {'label': 'Teacher', 'sinhala': 'ගුරුවරයා', 'synonyms': ['ගුරුවරයා', 'ගුරුතුමා', 'සර්', 'ගුරුවරිය', 'ගුරුතුමී', 'මිස්', 'ගුරුමිය']},
    "CONCEPT_TEAR": {'label': 'Tear', 'sinhala': 'ඉරනවා', 'synonyms': ['ඉරනවා', 'ඉරන්න', 'ඉරුවා']},
    "CONCEPT_TECHNOLOGY": {'label': 'Technology', 'sinhala': 'තාක්ෂණය', 'synonyms': ['තාක්ෂණය']},
    "CONCEPT_TEETH": {'label': 'Teeth', 'sinhala': 'දත්', 'synonyms': ['දත්']},
    "CONCEPT_TELEPHONE": {'label': 'Telephone', 'sinhala': 'දුරකථනය', 'synonyms': ['දුරකථනය', 'ටෙලිෆෝන්']},
    "CONCEPT_TELL": {'label': 'Tell', 'sinhala': 'කියනවා', 'synonyms': ['කියනවා', 'කියන්න', 'කිව්වා']},
    "CONCEPT_TEMPLE": {'label': 'Temple', 'sinhala': 'පන්සල', 'synonyms': ['පන්සල', 'පන්සල්', 'ආරාමය']},
    "CONCEPT_TEXT": {'label': 'Text', 'sinhala': 'පණිවිඩය', 'synonyms': ['පණිවිඩය', 'මැසේජ් කරනවා', 'මැසේජ්']},
    "CONCEPT_THAN": {'label': 'Than', 'sinhala': 'වඩා', 'synonyms': ['වඩා']},
    "CONCEPT_THANK_YOU": {'label': 'Thank you', 'sinhala': 'ස්තුතියි', 'synonyms': ['ස්තුතියි', 'බොහොම ස්තුතියි', 'ස්තූතියි']},
    "CONCEPT_THEY": {'label': 'They', 'sinhala': 'එයාලා', 'synonyms': ['එයාලා', 'ඔවුන්', 'ඒගොල්ලෝ']},
    "CONCEPT_THIEF": {'label': 'Thief', 'sinhala': 'හොරා', 'synonyms': ['හොරා']},
    "CONCEPT_THINK": {'label': 'Think', 'sinhala': 'හිතනවා', 'synonyms': ['හිතනවා', 'හිතන්න', 'හිතුවා']},
    "CONCEPT_THIRSTY": {'label': 'Thirsty', 'sinhala': 'තිබහයි', 'synonyms': ['තිබහයි', 'තිබහ']},
    "CONCEPT_THROW": {'label': 'Throw', 'sinhala': 'විසි කරනවා', 'synonyms': ['විසි කරනවා', 'විසි කරන්න', 'විසි කළා']},
    "CONCEPT_THURSDAY": {'label': 'Thursday', 'sinhala': 'බ්\u200dරහස්පතින්දා', 'synonyms': ['බ්\u200dරහස්පතින්දා']},
    "CONCEPT_TIME": {'label': 'Time', 'sinhala': 'කාලය', 'synonyms': ['කාලය', 'වෙලාව']},
    "CONCEPT_TIRE": {'label': 'Tire', 'sinhala': 'ටයර් එක', 'synonyms': ['ටයර් එක', 'ටයර්', 'රෝදය']},
    "CONCEPT_TIRED": {'label': 'Tired', 'sinhala': 'මහන්සි', 'synonyms': ['මහන්සි', 'කලුගැට']},
    "CONCEPT_TO": {'label': 'To', 'sinhala': 'ට', 'synonyms': ['ට', 'වෙත']},
    "CONCEPT_TODAY": {'label': 'Today', 'sinhala': 'අද', 'synonyms': ['අද']},
    "CONCEPT_TOMORROW": {'label': 'Tomorrow', 'sinhala': 'හෙට', 'synonyms': ['හෙට']},
    "CONCEPT_TORTOISE": {'label': 'Tortoise', 'sinhala': 'ඉබ්බා', 'synonyms': ['ඉබ්බා']},
    "CONCEPT_TRAIN": {'label': 'Train', 'sinhala': 'කෝච්චිය', 'synonyms': ['කෝච්චිය', 'දුම්රිය', 'කෝච්චි']},
    "CONCEPT_TRAIN_STATION": {'label': 'Train station', 'sinhala': 'දුම්රිය ස්ථානය', 'synonyms': ['දුම්රිය ස්ථානය', 'ස්ටේෂන් එක', 'දුම්රියපොළ']},
    "CONCEPT_TREE": {'label': 'Tree', 'sinhala': 'ගස', 'synonyms': ['ගස', 'ගහ', 'ගස්']},
    "CONCEPT_TRUST": {'label': 'Trust', 'sinhala': 'විශ්වාස කරනවා', 'synonyms': ['විශ්වාස කරනවා', 'විශ්වාස']},
    "CONCEPT_TUESDAY": {'label': 'Tuesday', 'sinhala': 'අඟහරුවාදා', 'synonyms': ['අඟහරුවාදා']},
    "CONCEPT_UGLY": {'label': 'Ugly', 'sinhala': 'කැත', 'synonyms': ['කැත']},
    "CONCEPT_UNCLE": {'label': 'Uncle', 'sinhala': 'මාමා', 'synonyms': ['මාමා', 'මාමේ']},
    "CONCEPT_UNDERSTAND": {'label': 'Understand', 'sinhala': 'තේරෙනවා', 'synonyms': ['තේරෙනවා', 'තේරුම් ගන්න', 'තේරුනා', 'තේරුණා']},
    "CONCEPT_UNTIL": {'label': 'Until', 'sinhala': 'වෙනකම්', 'synonyms': ['වෙනකම්', 'තුරු']},
    "CONCEPT_UP": {'label': 'Up', 'sinhala': 'උඩ', 'synonyms': ['උඩ', 'ඉහළ']},
    "CONCEPT_US": {'label': 'Us', 'sinhala': 'අපි', 'synonyms': ['අපි', 'අපිට']},
    "CONCEPT_USE": {'label': 'Use', 'sinhala': 'පාවිච්චි කරනවා', 'synonyms': ['පාවිච්චි කරනවා', 'භාවිතා කරනවා', 'භාවිතා']},
    "CONCEPT_VAN": {'label': 'Van', 'sinhala': 'වෑන් එක', 'synonyms': ['වෑන් එක', 'වෑන්', 'වෑන් රථය']},
    "CONCEPT_VEHICLE": {'label': 'Vehicle', 'sinhala': 'වාහනය', 'synonyms': ['වාහනය', 'වාහනේ', 'වාහන']},
    "CONCEPT_VISIT": {'label': 'Visit', 'sinhala': 'Visit', 'synonyms': ['Visit']},
    "CONCEPT_WALK": {'label': 'Walk', 'sinhala': 'ඇවිදිනවා', 'synonyms': ['ඇවිදිනවා', 'ඇවිදින්න', 'ඇවිද්දා', 'ගමන් කරනවා']},
    "CONCEPT_WANT": {'label': 'Want', 'sinhala': 'ඕන', 'synonyms': ['ඕන', 'අවශ්\u200dයයි', 'ඕනේ']},
    "CONCEPT_WASH": {'label': 'Wash', 'sinhala': 'සෝදනවා', 'synonyms': ['සෝදනවා', 'සෝදන්න', 'සේදුවා']},
    "CONCEPT_WATCH": {'label': 'Watch', 'sinhala': 'බලනවා', 'synonyms': ['බලනවා', 'බලන්න', 'බැලුවා', 'Watch', 'නරඹන්න']},
    "CONCEPT_WATER": {'label': 'Water', 'sinhala': 'වතුර', 'synonyms': ['වතුර', 'ජලය', 'පානීය ජලය']},
    "CONCEPT_WEATHER": {'label': 'Weather', 'sinhala': 'කාලගුණය', 'synonyms': ['කාලගුණය']},
    "CONCEPT_WEDNESDAY": {'label': 'Wednesday', 'sinhala': 'බදාදා', 'synonyms': ['බදාදා']},
    "CONCEPT_WEEK": {'label': 'Week', 'sinhala': 'සතිය', 'synonyms': ['සතිය']},
    "CONCEPT_WELCOME": {'label': 'Welcome', 'sinhala': 'සාදරයෙන් පිළිගනිමු', 'synonyms': ['සාදරයෙන් පිළිගනිමු']},
    "CONCEPT_WHAT": {'label': 'What', 'sinhala': 'මොකද්ද', 'synonyms': ['මොකද්ද', 'මොනවද']},
    "CONCEPT_WHEN": {'label': 'When', 'sinhala': 'කවදාද', 'synonyms': ['කවදාද', 'කවද්ද']},
    "CONCEPT_WHERE": {'label': 'Where', 'sinhala': 'කොහෙද', 'synonyms': ['කොහෙද', 'කොයි තැන']},
    "CONCEPT_WHITE": {'label': 'White', 'sinhala': 'සුදු', 'synonyms': ['සුදු']},
    "CONCEPT_WHO": {'label': 'Who', 'sinhala': 'කවුද', 'synonyms': ['කවුද', 'කව්ද']},
    "CONCEPT_WHOM": {'label': 'Whom', 'sinhala': 'කාටද', 'synonyms': ['කාටද']},
    "CONCEPT_WHOSE": {'label': 'Whose', 'sinhala': 'කාගෙද', 'synonyms': ['කාගෙද']},
    "CONCEPT_WHY": {'label': 'Why', 'sinhala': 'ඇයි', 'synonyms': ['ඇයි', 'හේතුව මොකද්ද']},
    "CONCEPT_WIFE": {'label': 'Wife', 'sinhala': 'බිරිඳ', 'synonyms': ['බිරිඳ', 'නෝනා', 'වයිෆ්', 'භාර්යාව']},
    "CONCEPT_WINDOW": {'label': 'Window', 'sinhala': 'ජනේලය', 'synonyms': ['ජනේලය', 'ජනෙල්']},
    "CONCEPT_WORK": {'label': 'Work', 'sinhala': 'වැඩ කරනවා', 'synonyms': ['වැඩ කරනවා', 'වැඩ', 'රැකියාව කරනවා']},
    "CONCEPT_WRITE": {'label': 'Write', 'sinhala': 'ලියනවා', 'synonyms': ['ලියනවා', 'ලියන්න', 'ලිව්වා', 'ලියවන්න']},
    "CONCEPT_WRONG": {'label': 'Wrong', 'sinhala': 'වැරදි', 'synonyms': ['වැරදි']},
    "CONCEPT_YEAR": {'label': 'Year', 'sinhala': 'අවුරුද්ද', 'synonyms': ['අවුරුද්ද']},
    "CONCEPT_YELLOW": {'label': 'Yellow', 'sinhala': 'කහ', 'synonyms': ['කහ']},
    "CONCEPT_YES": {'label': 'Yes', 'sinhala': 'ඔව්', 'synonyms': ['ඔව්']},
    "CONCEPT_YESTERDAY": {'label': 'Yesterday', 'sinhala': 'ඊයේ', 'synonyms': ['ඊයේ']},
    "CONCEPT_YOU": {'label': 'You', 'sinhala': 'ඔයා', 'synonyms': ['ඔයා', 'ඔබ', 'තමුසේ', 'ඔහේ']},
    "CONCEPT_YOUNGER_BRO": {'label': 'Younger bro', 'sinhala': 'මල්ලි', 'synonyms': ['මල්ලි', 'මල්ලී', 'මල්ලියේ']},
    "CONCEPT_YOUNGER_SISTER": {'label': 'Younger sister', 'sinhala': 'නංගි', 'synonyms': ['නංගි', 'නංගී', 'නංගියේ', 'නංගා']},
}

# --- STEP 3: CONCEPT NORMALIZATION LAYER (STRATEGY A) ---
# Maps Unsupported Concept IDs -> Supported Concept IDs
CONCEPT_NORMALIZATION_MAP = {
    "CONCEPT_READ": "CONCEPT_STUDY",
    "CONCEPT_LOOK_READ": "CONCEPT_STUDY",
    "CONCEPT_WATCH": "CONCEPT_SEE", # Example if Watch video is missing
    # Add more mappings as verified against dataset
}

def get_concept_by_sinhala(word):
    for cid, data in CONCEPT_DEFINITIONS.items():
        if word in data['synonyms']:
            return cid
    return None

def get_label_by_concept(cid):
    return CONCEPT_DEFINITIONS.get(cid, {}).get('label')

def get_sinhala_display(cid):
    return CONCEPT_DEFINITIONS.get(cid, {}).get('sinhala')

def get_all_synonyms():
    """Returns a list of all Sinhala synonyms across all concepts."""
    all_synonyms = []
    for data in CONCEPT_DEFINITIONS.values():
        all_synonyms.extend(data['synonyms'])
    return list(set(all_synonyms))

def normalize_concept(cid):
    """
    Step 3: Maps OOV Concepts to Supported Concepts
    Strategy A: Manual Map
    Strategy B: (Caller handles dynamic lookup if this returns same CID)
    """
    return CONCEPT_NORMALIZATION_MAP.get(cid, cid)
