"""
Model Loader Module
Handles loading the Keras model and class labels for inference
"""

import os
import logging
from tensorflow import keras

logger = logging.getLogger(__name__)

# Path to the hand+pose model (trained with 300 features - pose + hand landmarks)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "best_sign_model_hands.keras")

# Path to the class labels file generated by retrain_fixed.py
LABELS_PATH = os.path.join(os.path.dirname(__file__), "class_labels_hands.txt")

# Fallback to pose-only model if hands model not yet trained
MODEL_PATH_FALLBACK = os.path.join(os.path.dirname(__file__), "best_sign_model_fixed.keras")
LABELS_PATH_FALLBACK = os.path.join(os.path.dirname(__file__), "class_labels_fixed.txt")

_active_model_path = None
_active_labels_path = None


def _select_model_path():
    if os.path.exists(MODEL_PATH):
        return MODEL_PATH
    logger.warning(f"Hands model not found at: {MODEL_PATH}, trying fallback...")
    if os.path.exists(MODEL_PATH_FALLBACK):
        return MODEL_PATH_FALLBACK
    return None


def _labels_path_for_model(model_path):
    if model_path == MODEL_PATH:
        return LABELS_PATH
    if model_path == MODEL_PATH_FALLBACK:
        return LABELS_PATH_FALLBACK
    return LABELS_PATH_FALLBACK


def load_model():
    """
    Load the Keras model from disk.

    Returns:
        Loaded Keras model ready for inference

    Raises:
        FileNotFoundError: If model file doesn't exist
        Exception: If model loading fails
    """
    global _active_model_path

    model_path = _select_model_path()
    if model_path is None:
        error_msg = (
            f"Model file not found at: {MODEL_PATH} or {MODEL_PATH_FALLBACK}\n"
            "Please download the model .keras file from Kaggle and place it "
            "in the backend directory."
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)

    try:
        logger.info(f"Loading model from: {model_path}")
        model = keras.models.load_model(model_path)
        _active_model_path = model_path
        logger.info(f"Model loaded successfully from: {model_path}")
        logger.info(f"Model input shape : {model.input_shape}")
        logger.info(f"Model output shape: {model.output_shape}")
        return model

    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        raise


def get_class_labels():
    """
    Load class labels from class_labels_fixed.txt.

    The file is generated by retrain_fixed.py and contains one label per line
    in the format 'Category/Subcategory', e.g. 'Adjectives/Bad'.

    Returns:
        List of class label strings matching the model's output indices

    Raises:
        FileNotFoundError: If labels file doesn't exist
    """
    global _active_labels_path

    model_path = _active_model_path or _select_model_path()
    labels_path = _labels_path_for_model(model_path)

    if not os.path.exists(labels_path):
        error_msg = (
            f"Class labels file not found at: {labels_path}\n"
            "Please place the label file that was generated with the active "
            "model in the backend directory."
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)

    with open(labels_path, "r", encoding="utf-8") as f:
        labels = [line.strip() for line in f if line.strip()]

    _active_labels_path = labels_path
    logger.info(f"Loaded {len(labels)} class labels from {labels_path}")
    return labels


def get_num_classes():
    """Return the number of classes."""
    return len(get_class_labels())


def get_active_model_path():
    """Return the model path selected by load_model()."""
    return _active_model_path


def get_active_labels_path():
    """Return the labels path selected by get_class_labels()."""
    return _active_labels_path
