"""
Model Loader Module
Handles loading the Keras model and defining class labels
"""

import os
import logging
from tensorflow import keras

logger = logging.getLogger(__name__)

# Path to the model file (relative to backend directory)
# NEW MODEL: Uses all 33 landmarks (132 features) instead of just wrist (4 features)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "best_sign_model_full_features.keras")

# Sign language class labels (383 classes from SSL400 dataset)
# Extracted from Kaggle training output - sorted alphabetically by Category/Subcategory
CLASS_LABELS = [
    "Adjectives/Bad",
    "Adjectives/Beautiful",
    "Adjectives/Careful",
    "Adjectives/Cold",
    "Adjectives/Deaf",
    "Adjectives/Deep",
    "Adjectives/Different",
    "Adjectives/Difficult",
    "Adjectives/Double",
    "Adjectives/Fast",
    "Adjectives/Fat",
    "Adjectives/Free",
    "Adjectives/Full",
    "Adjectives/Good",
    "Adjectives/Happy",
    "Adjectives/Hard",
    "Adjectives/Healthy",
    "Adjectives/High",
    "Adjectives/Independent",
    "Adjectives/Less",
    "Adjectives/Loose",
    "Adjectives/Low",
    "Adjectives/Next",
    "Adjectives/Nice",
    "Adjectives/Not good",
    "Adjectives/Old",
    "Adjectives/Past",
    "Adjectives/Positive",
    "Adjectives/Present",
    "Adjectives/Quick",
    "Adjectives/Rich",
    "Adjectives/Same",
    "Adjectives/Senior",
    "Adjectives/Small",
    "Adjectives/Soft",
    "Adjectives/Strong",
    "Adjectives/Thirsty",
    "Adjectives/Tight",
    "Adjectives/Ugly",
    "Adjectives/Welcome",
    "Adjectives/Wrong",
    "Adverb/Again",
    "Adverb/Also",
    "Adverb/Can",
    "Adverb/Cant",
    "Adverb/Clearly",
    "Adverb/Dont",
    "Adverb/Dont know",
    "Adverb/Here",
    "Adverb/Instead",
    "Adverb/Never",
    "Adverb/Not like (dislike)",
    "Adverb/When",
    "Adverb/Where",
    "Adverb/Why",
    "Colors/Black",
    "Colors/Blue",
    "Colors/Brown",
    "Colors/Color",
    "Colors/Gold",
    "Colors/Gray",
    "Colors/Green",
    "Colors/Grey",
    "Colors/Orange",
    "Colors/Pink",
    "Colors/Purple",
    "Colors/Red",
    "Colors/White",
    "Colors/Yellow",
    "Conjunctions/Or",
    "Days/Day",
    "Days/Day after tomorrow",
    "Days/Evening",
    "Days/Friday",
    "Days/Good evening",
    "Days/Good morning",
    "Days/Good night",
    "Days/Hour",
    "Days/Monday",
    "Days/Morning",
    "Days/Night",
    "Days/Saturday",
    "Days/Seconds",
    "Days/Sunday",
    "Days/Thursday",
    "Days/Time",
    "Days/Today",
    "Days/Tomorrow",
    "Days/Tuesday",
    "Days/Wednesday",
    "Days/Week",
    "Days/Yesterday",
    "Determiner/No",
    "Greetings/Alright",
    "Greetings/Ayubowan",
    "Greetings/Hello",
    "Greetings/How are you",
    "Greetings/Thank you",
    "Interjection/Yes",
    "Months/April",
    "Months/August",
    "Months/December",
    "Months/February",
    "Months/January",
    "Months/July",
    "Months/June",
    "Months/March",
    "Months/May",
    "Months/Month",
    "Months/November",
    "Months/October",
    "Months/September",
    "Months/Year",
    "Nouns/Article",
    "Nouns/Bag",
    "Nouns/Bed",
    "Nouns/Book",
    "Nouns/Camera",
    "Nouns/Card",
    "Nouns/Cat",
    "Nouns/Ceiling fan",
    "Nouns/Cell phone",
    "Nouns/Chain",
    "Nouns/Children",
    "Nouns/Choice",
    "Nouns/Clothing",
    "Nouns/Computer",
    "Nouns/Cow",
    "Nouns/Crocodile",
    "Nouns/Culture",
    "Nouns/Door",
    "Nouns/Elephant",
    "Nouns/Eye",
    "Nouns/Eyes",
    "Nouns/Face",
    "Nouns/Fever",
    "Nouns/Flower",
    "Nouns/Food",
    "Nouns/Group",
    "Nouns/Gun",
    "Nouns/Hat",
    "Nouns/He",
    "Nouns/Health",
    "Nouns/Hill",
    "Nouns/How many",
    "Nouns/How much",
    "Nouns/I",
    "Nouns/Impact",
    "Nouns/Internet",
    "Nouns/Key",
    "Nouns/Laptop",
    "Nouns/List",
    "Nouns/Lock",
    "Nouns/Middle",
    "Nouns/Milk",
    "Nouns/Mind",
    "Nouns/Money",
    "Nouns/Moon",
    "Nouns/Movie",
    "Nouns/My",
    "Nouns/Network",
    "Nouns/None",
    "Nouns/Ok",
    "Nouns/Our",
    "Nouns/Paint",
    "Nouns/Part",
    "Nouns/Path",
    "Nouns/Peace",
    "Nouns/Pencil",
    "Nouns/Phone",
    "Nouns/Pocket",
    "Nouns/Point",
    "Nouns/Problem",
    "Nouns/Radio",
    "Nouns/Ring",
    "Nouns/Sand",
    "Nouns/Saree",
    "Nouns/Shirt",
    "Nouns/Sign",
    "Nouns/Sign language",
    "Nouns/Skirt",
    "Nouns/Society",
    "Nouns/Song",
    "Nouns/Squirrel",
    "Nouns/Street",
    "Nouns/Structure",
    "Nouns/Suit",
    "Nouns/Table",
    "Nouns/Tea",
    "Nouns/Team",
    "Nouns/Technology",
    "Nouns/Telephone",
    "Nouns/They",
    "Nouns/Tree",
    "Nouns/Weather",
    "Nouns/Who",
    "Nouns/Whom",
    "Nouns/Whose",
    "Nouns/Window",
    "Nouns/You",
    "Numbers/1. one",
    "Numbers/10. ten",
    "Numbers/11. eleven",
    "Numbers/12. twelve",
    "Numbers/13. thirteen",
    "Numbers/14. fourteen",
    "Numbers/15. fifteen",
    "Numbers/16. sixteen",
    "Numbers/17. seventeen",
    "Numbers/18. eighteen",
    "Numbers/19. nineteen",
    "Numbers/2. two",
    "Numbers/20. twenty",
    "Numbers/3. three",
    "Numbers/4. four",
    "Numbers/5. five",
    "Numbers/6. six",
    "Numbers/7. seven",
    "Numbers/8. eight",
    "Numbers/9. nine",
    "Numbers/Addition",
    "Numbers/Count",
    "Numbers/Divide",
    "Numbers/Equal",
    "Numbers/Multiplication",
    "Numbers/Subtraction",
    "People/Aunt",
    "People/Baby",
    "People/Bro",
    "People/Brother in law",
    "People/Child",
    "People/Daughter",
    "People/Doctor",
    "People/Elder bro",
    "People/Elder sister",
    "People/Families",
    "People/Family",
    "People/Father",
    "People/Grand father",
    "People/Grand mother",
    "People/Grand son",
    "People/Husband",
    "People/Lady",
    "People/Man",
    "People/Mother",
    "People/Player",
    "People/Police",
    "People/Relations",
    "People/She",
    "People/Sister",
    "People/Sister in law",
    "People/Son",
    "People/Thief",
    "People/Uncle",
    "People/Us",
    "People/Wife",
    "People/Younger bro",
    "People/Younger sister",
    "Places/Airport",
    "Places/Bank",
    "Places/Bus station",
    "Places/Church",
    "Places/Hospital",
    "Places/House",
    "Places/Location",
    "Places/Next door",
    "Places/Police station",
    "Places/Road",
    "Places/Shop",
    "Places/Temple",
    "Places/Train station",
    "Preposition/After",
    "Preposition/Around",
    "Preposition/In",
    "Preposition/Inside",
    "Preposition/Near",
    "Preposition/On",
    "Preposition/Out",
    "Preposition/Over",
    "Preposition/Than",
    "Preposition/To",
    "Preposition/Until",
    "Preposition/Up",
    "Vehicles/Bicycle",
    "Vehicles/Boat",
    "Vehicles/Bus",
    "Vehicles/Car",
    "Vehicles/Motorcycle",
    "Vehicles/Plane",
    "Vehicles/Tire",
    "Vehicles/Train",
    "Vehicles/Van",
    "Vehicles/Vehicle",
    "Verbs/Allow",
    "Verbs/Bathe",
    "Verbs/Boil",
    "Verbs/Break",
    "Verbs/Bring",
    "Verbs/Buy",
    "Verbs/Carry",
    "Verbs/Change",
    "Verbs/Choose",
    "Verbs/Click",
    "Verbs/Come",
    "Verbs/Connect",
    "Verbs/Cook",
    "Verbs/Copy",
    "Verbs/Cough",
    "Verbs/Cover",
    "Verbs/Cry",
    "Verbs/Cut",
    "Verbs/Dance",
    "Verbs/Done",
    "Verbs/Draw",
    "Verbs/Drink",
    "Verbs/Eat",
    "Verbs/Enter",
    "Verbs/Erase",
    "Verbs/Exchange",
    "Verbs/Feel",
    "Verbs/Fight",
    "Verbs/Follow",
    "Verbs/Get up",
    "Verbs/Give",
    "Verbs/Go",
    "Verbs/Guide",
    "Verbs/Hang",
    "Verbs/Hear",
    "Verbs/Help",
    "Verbs/Hit",
    "Verbs/How",
    "Verbs/I know",
    "Verbs/Jump",
    "Verbs/Knock",
    "Verbs/Laugh",
    "Verbs/Lead",
    "Verbs/Let",
    "Verbs/Like",
    "Verbs/Listen",
    "Verbs/Look",
    "Verbs/Love",
    "Verbs/Make",
    "Verbs/Meet",
    "Verbs/Now",
    "Verbs/Open",
    "Verbs/Order",
    "Verbs/Peeing",
    "Verbs/Play",
    "Verbs/Pull",
    "Verbs/Put",
    "Verbs/Quickly",
    "Verbs/Run",
    "Verbs/Scratch",
    "Verbs/Search",
    "Verbs/See",
    "Verbs/Select",
    "Verbs/Sell",
    "Verbs/Show",
    "Verbs/Sit",
    "Verbs/Sleep",
    "Verbs/Smile",
    "Verbs/Stop",
    "Verbs/Study",
    "Verbs/Sweep",
    "Verbs/Swim",
    "Verbs/Take",
    "Verbs/Talk",
    "Verbs/Teach",
    "Verbs/Tear",
    "Verbs/Tell",
    "Verbs/Text",
    "Verbs/Think",
    "Verbs/Throw",
    "Verbs/Trust",
    "Verbs/Understand",
    "Verbs/Use",
    "Verbs/Visit",
    "Verbs/Walk",
    "Verbs/Want",
    "Verbs/Wash",
    "Verbs/Watch",
    "Verbs/Work",
    "Verbs/Write",
]

# Model achieved 67.33% accuracy with these labels (improved from 61.88%)


def load_model():
    """
    Load the Keras model from disk
    
    Returns:
        Loaded Keras model ready for inference
        
    Raises:
        FileNotFoundError: If model file doesn't exist
        Exception: If model loading fails
    """
    logger.info(f"Loading model from: {MODEL_PATH}")
    
    # Check if model file exists
    if not os.path.exists(MODEL_PATH):
        error_msg = f"Model file not found at: {MODEL_PATH}"
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)
    
    try:
        # Load the Keras model
        model = keras.models.load_model(MODEL_PATH)
        logger.info("Model loaded successfully!")
        
        # Log model summary
        logger.info(f"Model input shape: {model.input_shape}")
        logger.info(f"Model output shape: {model.output_shape}")
        
        return model
        
    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        raise


def get_class_labels():
    """
    Get the list of class labels
    
    Returns:
        List of class label strings
    """
    return CLASS_LABELS


def get_num_classes():
    """
    Get the number of classes
    
    Returns:
        Number of classes as integer
    """
    return len(CLASS_LABELS)
