"""
Model Loader Module
Handles loading the Keras model and class labels for inference
"""

import os
import logging
from tensorflow import keras

logger = logging.getLogger(__name__)

# Path to the new fixed model (trained with correct pipeline - no data leakage)
MODEL_PATH = os.path.join(os.path.dirname(__file__), "best_sign_model_fixed.keras")

# Path to the class labels file generated by retrain_fixed.py
LABELS_PATH = os.path.join(os.path.dirname(__file__), "class_labels_fixed.txt")


def load_model():
    """
    Load the Keras model from disk.

    Returns:
        Loaded Keras model ready for inference

    Raises:
        FileNotFoundError: If model file doesn't exist
        Exception: If model loading fails
    """
    logger.info(f"Loading model from: {MODEL_PATH}")

    if not os.path.exists(MODEL_PATH):
        error_msg = (
            f"Model file not found at: {MODEL_PATH}\n"
            "Please download best_sign_model_fixed.keras from Kaggle and place it "
            "in the backend directory."
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)

    try:
        model = keras.models.load_model(MODEL_PATH)
        logger.info("Model loaded successfully!")
        logger.info(f"Model input shape : {model.input_shape}")
        logger.info(f"Model output shape: {model.output_shape}")
        return model

    except Exception as e:
        logger.error(f"Failed to load model: {e}")
        raise


def get_class_labels():
    """
    Load class labels from class_labels_fixed.txt.

    The file is generated by retrain_fixed.py and contains one label per line
    in the format 'Category/Subcategory', e.g. 'Adjectives/Bad'.

    Returns:
        List of class label strings matching the model's output indices

    Raises:
        FileNotFoundError: If labels file doesn't exist
    """
    if not os.path.exists(LABELS_PATH):
        error_msg = (
            f"Class labels file not found at: {LABELS_PATH}\n"
            "Please download class_labels_fixed.txt from Kaggle and place it "
            "in the backend directory."
        )
        logger.error(error_msg)
        raise FileNotFoundError(error_msg)

    with open(LABELS_PATH, "r", encoding="utf-8") as f:
        labels = [line.strip() for line in f if line.strip()]

    logger.info(f"Loaded {len(labels)} class labels from {LABELS_PATH}")
    return labels


def get_num_classes():
    """Return the number of classes."""
    return len(get_class_labels())
